services:
  backend:
    container_name: backend-mtg
    build: ./MTG_Backend_sqlite_TypeOrm
    command: npm run start
    volumes:
      - ./MTG_Backend_sqlite_TypeOrm/src/:/app/src
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      APP_SECRET: ${APP_SECRET}
      BACKEND_PORT: ${BACKEND_PORT}

  frontend:
    container_name: frontend-mtg
    build: ./MTG_front_react
    volumes:
      - ./MTG_front_react/src/:/app/src
      - ./MTG_front_react/public/:/app/public
    environment:
      VITE_GATEWAY_PORT: ${VITE_GATEWAY_PORT}

  database:
    container_name: database-mtg
    image: postgres
    volumes:
      - ./persist/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_HOST: ${DB_HOST}

  vizualizer:
    container_name: vizualizer-mtg
    image: adminer

  gateway:
    container_name: gateway-mtg
    image: nginx
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/dev.conf.template
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    command: /bin/bash -c "envsubst '$$BACKEND_PORT' < /etc/nginx/conf.d/dev.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
