services:
  backend:
    build: ./
    ports:
      - 4000:4000
    command: npm run start
    volumes:
      - ./src/:/app/src
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      APP_SECRET: ${APP_SECRET}

  database:
    container_name: FullStack_MTG_DB
    image: postgres
    volumes:
      - ./persist/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_HOST: ${DB_HOST}

  vizualizer:
    container_name: vizualizer_FullStack_MTG
    image: adminer
    ports:
      - "8080:8080"

  gateway:
    container_name: gateway_FullStack_MTG
    image: nginx
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
